# Generated by Django 5.2.8 on 2025-11-13 02:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "snmp_ro_community",
                    models.CharField(default="public", max_length=100),
                ),
                (
                    "snmp_rw_community",
                    models.CharField(default="private", max_length=100),
                ),
                (
                    "ssh_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ssh_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "enable_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "dev_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.devicetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetricType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("snmp", "SNMP"),
                            ("grpc", "gRPC"),
                            ("telemetry", "Telemetry"),
                            ("restconf", "RESTCONF"),
                            ("other", "Other"),
                        ],
                        default="snmp",
                        max_length=50,
                    ),
                ),
                ("metric_path", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="devices_met_name_75836b_idx"),
                    models.Index(
                        fields=["protocol"], name="devices_met_protoco_4e42e4_idx"
                    ),
                ],
                "unique_together": {("name", "protocol", "metric_path")},
            },
        ),
        migrations.CreateModel(
            name="MetricMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logical_name", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.metrictype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["logical_name"], name="devices_met_logical_d04ba4_idx"
                    )
                ],
                "unique_together": {("logical_name", "metric_type")},
            },
        ),
        migrations.CreateModel(
            name="DeviceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("metrics", models.JSONField()),
                ("success", models.BooleanField(default=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.devicedb",
                    ),
                ),
                (
                    "metric_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="devices.metrictype",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="devices_dev_device__c419e7_idx",
                    ),
                    models.Index(
                        fields=["metric_type"], name="devices_dev_metric__dae16f_idx"
                    ),
                ],
            },
        ),
    ]
