# Generated by Django 5.2.8 on 2025-11-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="metrictype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="metrictype",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devices.devicetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="devicetype",
            unique_together={("vendor", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="metrictype",
            unique_together={("name", "protocol", "metric_path", "device_type")},
        ),
        migrations.AddIndex(
            model_name="metrictype",
            index=models.Index(
                fields=["device_type"], name="devices_met_device__d6bcc8_idx"
            ),
        ),
        migrations.AddField(
            model_name="devicetype",
            name="vendor_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="devices.vendor",
            ),
        ),
    ]
