# Generated by Django 5.2.8 on 2025-11-13 05:27

from django.db import migrations


def migrate_vendor(apps, schema_editor):
    DeviceType = apps.get_model("devices", "DeviceType")
    Vendor = apps.get_model("devices", "Vendor")

    for dt in DeviceType.objects.all():
        if dt.vendor:  # 原来的字符串
            vendor_obj = Vendor.objects.filter(name=dt.vendor).first()
            if vendor_obj:
                print(f"{dt.id}: Vendor already set -> {dt.vendor}")
                continue

            vendor_obj, created = Vendor.objects.get_or_create(name=dt.vendor)
            dt.vendor_rt = vendor_obj
            dt.save()
            print(f"{dt.id}: Vendor set -> {vendor_obj.name} (created={created})")            
            
class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_vendor_alter_metrictype_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_vendor),

    ]
