# Generated by Django 5.2.8 on 2025-11-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_migrate_vendor_to_fk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetype",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="devicetype",
            name="vendor",
        ),
    ]
