# Generated by Django 5.2.8 on 2025-11-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_devicetype_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devicetype",
            old_name="vendor_fk",
            new_name="vendor",
        ),
        migrations.AlterUniqueTogether(
            name="devicetype",
            unique_together={("vendor", "name")},
        ),
    ]
