# Generated by Django 5.2.8 on 2025-11-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_rename_vendor_fk_devicetype_vendor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetricMapping",
        ),
    ]
