# Generated by Django 5.2.8 on 2025-11-13 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_delete_metricmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logical_name", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="metrictype",
            name="devices_met_device__d6bcc8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="metrictype",
            unique_together={("name", "protocol", "metric_path")},
        ),
        migrations.AddField(
            model_name="metricmapping",
            name="device_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.devicetype"
            ),
        ),
        migrations.AddField(
            model_name="metricmapping",
            name="metric_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.metrictype"
            ),
        ),
        migrations.RemoveField(
            model_name="metrictype",
            name="device_type",
        ),
        migrations.AddIndex(
            model_name="metricmapping",
            index=models.Index(
                fields=["logical_name"], name="devices_met_logical_d04ba4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="metricmapping",
            unique_together={("logical_name", "metric_type")},
        ),
    ]
