# Generated by Django 5.2.8 on 2025-11-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_metricmapping_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="metricmapping",
            unique_together={("logical_name", "metric_type", "device_type")},
        ),
    ]
