input {
  beats {
    port => 5044
  }
}

filter {

  #
  # 1️⃣ 先判断 RFC5424（以年份开头）
  #
  if [message] =~ /^\</ and [message] =~ /^\<\d+\>\d+\s+\d{4}-\d{2}-\d{2}T/ {

    grok {
      match => {
        "message" => [
          "<%{NUMBER:syslog_priority}>%{NUMBER:syslog_version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:host} %{DATA:process}(?:\[%{NUMBER:pid}\])? %{DATA:msgid} %{DATA:structured} %{GREEDYDATA:msg}"
        ]
      }
    }

    date {
      match => [ "timestamp", "ISO8601" ]
    }

  } else {

    #
    # 2️⃣ RFC3164
    #
    grok {
      match => {
        "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} %{DATA:process}(?:\[%{NUMBER:pid}\])?: %{GREEDYDATA:msg}"
      }
    }

    date {
      match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      timezone => "UTC"
    }
  }

  #
  # 3️⃣ 按 process 分类（放在后面，确保字段存在）
  #
  if [process] =~ "ospfd" {
    mutate { add_field => { "log_type" => "ospf" } }
  } else if [process] =~ "Keepalived_vrrp" {
    mutate { add_field => { "log_type" => "vrrp" } }
  } else if [process] =~ "openvpn" {
    mutate { add_field => { "log_type" => "vpn" } }
  } else {
    mutate { add_field => { "log_type" => "other" } }
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "vyos-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
