[project]
name = "qyt-aiops-session-17"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "elasticsearch==8.14.0",
    "fastapi>=0.119.0",
    "flask>=3.1.2",
    "flask-jsonrpc>=3.0.1",
    "fonttools>=4.60.0",
    "gunicorn>=23.0.0",
    "influxdb>=5.3.2",
    "kamene>=0.32",
    "matplotlib>=3.10.6",
    "ncclient>=0.7.0",
    "netmiko>=4.6.0",
    "pandas>=2.3.2",
    "paramiko>=4.0.0",
    "psutil>=7.1.0",
    "psycopg2-binary>=2.9.10",
    "pyinstaller>=6.15.0",
    "pyshark>=0.6",
    "pysmi>=1.6.2",
    "pysnmp-mibs>=0.1.6",
    "pytz>=2025.2",
    "pyvmomi>=9.0.0.0",
    "qyt-libs",
    "scapy>=2.6.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.37.0",
    "xmltodict>=1.0.2",
]

[tool.uv.workspace]
members = [
    "external_libs/qyt_libs",
]

[tool.uv.sources]
qyt-libs = { workspace = true }
