[project]
name = "qyt-aiops-session-17"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kamene>=0.32",
    "paramiko>=4.0.0",
]
