[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "qyt_libs"
version = "0.9.0"
description = "qyt libs"
authors = [{name="Tingle"}]
requires-python = ">=3.11"