# ========== 全局 ==========
[agent]
  hostname = "telegraf-c9kv"
  interval = "10s"

# ========== OUTPUT ==========
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mytoken"
  organization = "mylab"
  bucket = "network_monitor"

# ========== SNMP 采集 ==========
[[inputs.snmp]]
  agents = ["udp://192.0.2.210:161"]
  version = 2
  community = "mylab"
  timeout = "5s"
  retries = 2
  name = "c9kv_snmp"

[[inputs.snmp.field]]
    name="sysuptime"
    oid="1.3.6.1.2.1.1.3.0"
[[inputs.snmp.field]]
    name="CPUTotal5sec"
    oid="1.3.6.1.4.1.9.9.109.1.1.1.1.3.7"
[[inputs.snmp.field]]
    name="MemoryUsed"
    oid="1.3.6.1.4.1.9.9.109.1.1.1.1.12.7"
[[inputs.snmp.field]]
    name="MemoryFree"
    oid="1.3.6.1.4.1.9.9.109.1.1.1.1.13.7"
[[inputs.snmp.field]]
    name="CPUTotal5sec-iosd"
    oid="1.3.6.1.4.1.9.2.1.56.0"
[[inputs.snmp.field]]
    name="MemoryUsed-iosd"
    oid="1.3.6.1.4.1.9.9.48.1.1.1.5.1"
[[inputs.snmp.field]]
    name="MemoryFree-iosd"
    oid="1.3.6.1.4.1.9.9.48.1.1.1.6.1"
[[inputs.snmp.table]]
name = "interface_table"
inherit_tags = ["hostname"]
[[inputs.snmp.table.field]]
  name = "ifDescr"
  oid = "1.3.6.1.2.1.2.2.1.2"
  is_tag = true
[[inputs.snmp.table.field]]
  name = "ifInOctets"
  oid = "1.3.6.1.2.1.2.2.1.10"
[[inputs.snmp.table.field]]
  name = "ifOutOctets"
  oid = "1.3.6.1.2.1.2.2.1.16"

# ========== gRPC Streaming Telemetry (Cisco MDT) ==========
[[inputs.cisco_telemetry_mdt]]
  transport = "grpc"
  service_address  = ":57500"



  # # ✅ CPU 利用率
  # [[inputs.cisco_telemetry_mdt.subscription]]
  #   name = "cpu"
  #   path = "Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization"

  # # ✅ 内存使用
  # [[inputs.cisco_telemetry_mdt.subscription]]
  #   name = "memory"
  #   path = "Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistics"

  # # ✅ 接口流量
  # [[inputs.cisco_telemetry_mdt.subscription]]
  #   name = "interfaces"
  #   path = "ietf-interfaces:interfaces-state"
