{
 "title": "MyLab",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "C9Kv 5秒 CPU利用率 from GNMI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"C9Kv\")\r\n  |> filter(fn: (r) => r[\"subscription\"] == \"666\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])"
    }
   ]
  },
  {
   "title": "C9Kv 5秒 CPU利用率 from SNMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"c9kv_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"CPUTotal5sec-iosd\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.0.2.210\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")"
    }
   ]
  },
  {
   "title": "C9Kv 内存利用率 from GNMI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_memory\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"C9Kv\")"
    }
   ]
  },
  {
   "title": "C9Kv 内存利用率 from SNMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"c9kv_snmp\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"MemoryUsed-iosd\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.0.2.210\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")"
    }
   ]
  },
  {
   "title": "C9Kv 接口速率 from GNMI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_kbps\" or r[\"_field\"] == \"tx_kbps\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"GigabitEthernet1/0/1\")\r\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface/statistics\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"C9Kv\")\r\n  |> filter(fn: (r) => r[\"subscription\"] == \"671\")\r\n  |> map(fn: (r) => ({ \r\n        r with\r\n        _field: r[\"name\"] + \" - \" + r[\"_field\"]\r\n     })\r\n  )"
    }
   ]
  },
  {
   "title": "C9Kv 接口速率 from SNMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"network_monitor\")\r\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface_table\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ifInOctets\" or r[\"_field\"] == \"ifOutOctets\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.0.2.210\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"telegraf-c9kv\")\r\n  |> filter(fn: (r) => r[\"ifDescr\"] == \"GigabitEthernet1/0/1\")\r\n  |> map(fn: (r) => ({ r with _value: r._value * 8 /1000 }))\r\n  |> derivative(unit: 1s, nonNegative: false) \r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field: if r._field == \"ifInOctets\" then r.ifDescr + \" -rx_kbps\" else r.ifDescr + \" -tx_kbps\"\r\n  }))\r\n"
    }
   ]
  }
 ]
}